### ISSUE TITLE
prevent travis from randomly failing

### ISSUE THREAD

**Issue by mastilver** [ericelliott/credential#42]
travis is randomly failing because of: `constantTimeCompare`

I guess we don't want to increase the alpha time

What about we change the travis script to
`npm run check || npm run check || npm run check`
So the tests are running at least three time before failing

**Comment by brianmhunt** [comment]
If the failing test is `constantEquals exposes no timings`, then the correct thing to do would be to either make the `alpha` larger (e.g. `0.005`) or increase `iterations`.  There's a trade-off; making `alpha` larger makes the test less sensitive.  Increasing `iterations` takes longer.

It is probably preferable to increase the `iterations`.

It probably would not make sense to run the tests three times, which is roughly the same as saying "there's no timing attack ... 1 out of 3 times." :smile: 

The other possibility is that `constantTimeCompare` is not actually constant time.  Likely if that has happened it is because of optimizations by the interpreter.  This'll happen regularly because optimizations are changing all the time, and vary on engine; the only correct long-term solution will eventually be to use WebCrypto API.

**Comment by mastilver** [comment]
Yeah, true, good point :smile: 

What about the iterations depends whether `'CI' in process.env` is true
so keep `2500` for local
And maybe `25000` for travis ?

**Comment by brianmhunt** [comment]
@mastilver That's a great idea.

**Comment by mastilver** [comment]
I'm reopening this one as tests are still failing randomly

@ericelliott Could you disable greenkeeper while we figure out how to make test more stable

**Comment by ericelliott** [comment]
Done.

**Comment by brianmhunt** [comment]
The underlying reason that the tests still fail is, quite possibly, because the constant-time comparison is never constant.

The [Node.js folks discussed this at some length](https://github.com/nodejs/node-v0.x-archive/issues/8560) some time ago, with the upshot being:

1. In Javascript there's no way to get around the optimizations of the compiler, interpreter, and processor, so constant time is nigh-unachievable; and
2. [a wisely-implemented Double-HMAC](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/) may achieve the equivalent by blinding the timing channel.

I would err on the side of preferring double-HMAC to constant-time comparison.  It doesn't look like a big fix, but one would have to wrap their head about it.

With a blind timing channel the stats tests ought to pass.

**Comment by ericelliott** [comment]
I'm open to a PR.

**Comment by ericelliott** [comment]
Closing all stale issues and PRs. Please update, ensure all tests pass, and reopen if you really want this in.
